version: '3'

services:

  hivemq:
    image: 'peez/hivemq'
    container_name: mqttbroker
    environment:
      - HIVEMQ_DISABLE_AUTH_PLUGIN=true

  postgresql:
    image: 'postgres:9-alpine'
    environment:
      - POSTGRES_USER=statelessasync
      - POSTGRES_PASSWORD=statelessasync
      - POSTGRES_DB=statelessasync
    ports:
      - "5432:5432"
    container_name: postgresql

  joynrbackend:
    image: "stateless-async-backend-services:latest"
    container_name: joynrbackend
    environment:
      - joynr_messaging_mqtt_brokeruris=tcp://mqttbroker:1883

  carsim:
    image: "stateless-async-car-sim:latest"
    container_name: carsim

  jee-consumer-1:
    image: "stateless-async-jee-consumer:latest"
    container_name: jee-consumer-1
    ports:
      - "8081:8080"

  jee-consumer-2:
    image: "stateless-async-jee-consumer:latest"
    container_name: jee-consumer-2
    ports:
      - "8082:8080"

  jee-consumer-3:
    image: "stateless-async-jee-consumer:latest"
    container_name: jee-consumer-3
    ports:
      - "8083:8080"

  java-consumer:
    image: "stateless-async-consumer:latest"
    container_name: java-consumer
