version: '3'

services:

  hivemq:
    image: 'hivemq/hivemq3'
    container_name: mqttbroker
    environment:
      - HIVEMQ_DISABLE_AUTH_PLUGIN=true

  joynrbackend:
    image: "custom-headers-backend-services:latest"
    container_name: joynrbackend
    environment:
      - joynr_messaging_mqtt_brokeruri=tcp://mqttbroker:1883
      - joynr_messaging_domainaccesscontrollerurl=tcp://mqttbroker:1883
      - joynr_messaging_discoverydirectoryurl=tcp://mqttbroker:1883

  jee-provider:
    image: "custom-headers-jee-provider:latest"
    container_name: jee-provider
    ports:
      - "8080:8080"

  jee-consumer:
    image: "custom-headers-jee-consumer:latest"
    container_name: jee-consumer
    ports:
      - "8081:8080"
